// ========== FIFA World Cup 2026 — Complete Team & Tournament Data ==========

// 48 teams with bilingual names, group assignment, and flag emojis
export const TEAMS = {
  MEX: { code: 'MEX', nameEn: 'Mexico', nameZh: '墨西哥', group: 'A', flag: '🇲🇽' },
  RSA: { code: 'RSA', nameEn: 'South Africa', nameZh: '南非', group: 'A', flag: '🇿🇦' },
  KOR: { code: 'KOR', nameEn: 'South Korea', nameZh: '韩国', group: 'A', flag: '🇰🇷' },
  CZE: { code: 'CZE', nameEn: 'Czechia', nameZh: '捷克', group: 'A', flag: '🇨🇿' },
  CAN: { code: 'CAN', nameEn: 'Canada', nameZh: '加拿大', group: 'B', flag: '🇨🇦' },
  BIH: { code: 'BIH', nameEn: 'Bosnia & Herzegovina', nameZh: '波黑', group: 'B', flag: '🇧🇦' },
  QAT: { code: 'QAT', nameEn: 'Qatar', nameZh: '卡塔尔', group: 'B', flag: '🇶🇦' },
  SUI: { code: 'SUI', nameEn: 'Switzerland', nameZh: '瑞士', group: 'B', flag: '🇨🇭' },
  BRA: { code: 'BRA', nameEn: 'Brazil', nameZh: '巴西', group: 'C', flag: '🇧🇷' },
  MAR: { code: 'MAR', nameEn: 'Morocco', nameZh: '摩洛哥', group: 'C', flag: '🇲🇦' },
  HAI: { code: 'HAI', nameEn: 'Haiti', nameZh: '海地', group: 'C', flag: '🇭🇹' },
  SCO: { code: 'SCO', nameEn: 'Scotland', nameZh: '苏格兰', group: 'C', flag: '🏴󠁧󠁢󠁳󠁣󠁴󠁿' },
  USA: { code: 'USA', nameEn: 'United States', nameZh: '美国', group: 'D', flag: '🇺🇸' },
  PAR: { code: 'PAR', nameEn: 'Paraguay', nameZh: '巴拉圭', group: 'D', flag: '🇵🇾' },
  AUS: { code: 'AUS', nameEn: 'Australia', nameZh: '澳大利亚', group: 'D', flag: '🇦🇺' },
  TUR: { code: 'TUR', nameEn: 'Türkiye', nameZh: '土耳其', group: 'D', flag: '🇹🇷' },
  GER: { code: 'GER', nameEn: 'Germany', nameZh: '德国', group: 'E', flag: '🇩🇪' },
  CUW: { code: 'CUW', nameEn: 'Curaçao', nameZh: '库拉索', group: 'E', flag: '🇨🇼' },
  CIV: { code: 'CIV', nameEn: 'Ivory Coast', nameZh: '科特迪瓦', group: 'E', flag: '🇨🇮' },
  ECU: { code: 'ECU', nameEn: 'Ecuador', nameZh: '厄瓜多尔', group: 'E', flag: '🇪🇨' },
  NED: { code: 'NED', nameEn: 'Netherlands', nameZh: '荷兰', group: 'F', flag: '🇳🇱' },
  JPN: { code: 'JPN', nameEn: 'Japan', nameZh: '日本', group: 'F', flag: '🇯🇵' },
  SWE: { code: 'SWE', nameEn: 'Sweden', nameZh: '瑞典', group: 'F', flag: '🇸🇪' },
  TUN: { code: 'TUN', nameEn: 'Tunisia', nameZh: '突尼斯', group: 'F', flag: '🇹🇳' },
  BEL: { code: 'BEL', nameEn: 'Belgium', nameZh: '比利时', group: 'G', flag: '🇧🇪' },
  EGY: { code: 'EGY', nameEn: 'Egypt', nameZh: '埃及', group: 'G', flag: '🇪🇬' },
  IRN: { code: 'IRN', nameEn: 'Iran', nameZh: '伊朗', group: 'G', flag: '🇮🇷' },
  NZL: { code: 'NZL', nameEn: 'New Zealand', nameZh: '新西兰', group: 'G', flag: '🇳🇿' },
  ESP: { code: 'ESP', nameEn: 'Spain', nameZh: '西班牙', group: 'H', flag: '🇪🇸' },
  CPV: { code: 'CPV', nameEn: 'Cape Verde', nameZh: '佛得角', group: 'H', flag: '🇨🇻' },
  KSA: { code: 'KSA', nameEn: 'Saudi Arabia', nameZh: '沙特阿拉伯', group: 'H', flag: '🇸🇦' },
  URU: { code: 'URU', nameEn: 'Uruguay', nameZh: '乌拉圭', group: 'H', flag: '🇺🇾' },
  FRA: { code: 'FRA', nameEn: 'France', nameZh: '法国', group: 'I', flag: '🇫🇷' },
  SEN: { code: 'SEN', nameEn: 'Senegal', nameZh: '塞内加尔', group: 'I', flag: '🇸🇳' },
  IRQ: { code: 'IRQ', nameEn: 'Iraq', nameZh: '伊拉克', group: 'I', flag: '🇮🇶' },
  NOR: { code: 'NOR', nameEn: 'Norway', nameZh: '挪威', group: 'I', flag: '🇳🇴' },
  ARG: { code: 'ARG', nameEn: 'Argentina', nameZh: '阿根廷', group: 'J', flag: '🇦🇷' },
  ALG: { code: 'ALG', nameEn: 'Algeria', nameZh: '阿尔及利亚', group: 'J', flag: '🇩🇿' },
  AUT: { code: 'AUT', nameEn: 'Austria', nameZh: '奥地利', group: 'J', flag: '🇦🇹' },
  JOR: { code: 'JOR', nameEn: 'Jordan', nameZh: '约旦', group: 'J', flag: '🇯🇴' },
  POR: { code: 'POR', nameEn: 'Portugal', nameZh: '葡萄牙', group: 'K', flag: '🇵🇹' },
  COD: { code: 'COD', nameEn: 'DR Congo', nameZh: '刚果(金)', group: 'K', flag: '🇨🇩' },
  UZB: { code: 'UZB', nameEn: 'Uzbekistan', nameZh: '乌兹别克斯坦', group: 'K', flag: '🇺🇿' },
  COL: { code: 'COL', nameEn: 'Colombia', nameZh: '哥伦比亚', group: 'K', flag: '🇨🇴' },
  ENG: { code: 'ENG', nameEn: 'England', nameZh: '英格兰', group: 'L', flag: '🏴󠁧󠁢󠁥󠁮󠁧󠁿' },
  CRO: { code: 'CRO', nameEn: 'Croatia', nameZh: '克罗地亚', group: 'L', flag: '🇭🇷' },
  GHA: { code: 'GHA', nameEn: 'Ghana', nameZh: '加纳', group: 'L', flag: '🇬🇭' },
  PAN: { code: 'PAN', nameEn: 'Panama', nameZh: '巴拿马', group: 'L', flag: '🇵🇦' },
  TBD: { code: 'TBD', nameEn: 'TBD', nameZh: '待定', group: '', flag: '❓' },
};

export const GROUPS = {
  A: ['MEX', 'RSA', 'KOR', 'CZE'],
  B: ['CAN', 'BIH', 'QAT', 'SUI'],
  C: ['BRA', 'MAR', 'HAI', 'SCO'],
  D: ['USA', 'PAR', 'AUS', 'TUR'],
  E: ['GER', 'CUW', 'CIV', 'ECU'],
  F: ['NED', 'JPN', 'SWE', 'TUN'],
  G: ['BEL', 'EGY', 'IRN', 'NZL'],
  H: ['ESP', 'CPV', 'KSA', 'URU'],
  I: ['FRA', 'SEN', 'IRQ', 'NOR'],
  J: ['ARG', 'ALG', 'AUT', 'JOR'],
  K: ['POR', 'COD', 'UZB', 'COL'],
  L: ['ENG', 'CRO', 'GHA', 'PAN'],
};

// Stage name translations
export const STAGE_NAMES = {
  'Group Stage': { en: 'Group Stage', zh: '小组赛' },
  'Round of 32': { en: 'Round of 32', zh: '32强赛' },
  'Round of 16': { en: 'Round of 16', zh: '16强赛' },
  'Quarter-finals': { en: 'Quarter-finals', zh: '四分之一决赛' },
  'Semi-finals': { en: 'Semi-finals', zh: '半决赛' },
  'Third Place': { en: 'Third Place', zh: '三四名决赛' },
  'Final': { en: 'Final', zh: '决赛' },
};

export const TOURNAMENT = {
  startDate: '2026-06-11',
  endDate: '2026-07-19',
  totalMatches: 104,
  totalTeams: 48,
  hostNations: ['Canada', 'Mexico', 'USA'],
  hostNationsZh: ['加拿大', '墨西哥', '美国'],
};

export const VENUES = [
  { city: 'Mexico City', cityZh: '墨西哥城', stadium: 'Estadio Azteca', stadiumZh: '阿兹特克体育场', country: 'Mexico', countryZh: '墨西哥' },
  { city: 'Monterrey', cityZh: '蒙特雷', stadium: 'Estadio BBVA', stadiumZh: 'BBVA体育场', country: 'Mexico', countryZh: '墨西哥' },
  { city: 'Guadalajara', cityZh: '瓜达拉哈拉', stadium: 'Estadio Akron', stadiumZh: '阿克伦体育场', country: 'Mexico', countryZh: '墨西哥' },
  { city: 'Toronto', cityZh: '多伦多', stadium: 'BMO Field', stadiumZh: 'BMO球场', country: 'Canada', countryZh: '加拿大' },
  { city: 'Vancouver', cityZh: '温哥华', stadium: 'BC Place', stadiumZh: 'BC广场', country: 'Canada', countryZh: '加拿大' },
  { city: 'East Rutherford', cityZh: '东卢瑟福', stadium: 'MetLife Stadium', stadiumZh: '大都会人寿体育场', country: 'USA', countryZh: '美国' },
  { city: 'Los Angeles', cityZh: '洛杉矶', stadium: 'SoFi Stadium', stadiumZh: 'SoFi体育场', country: 'USA', countryZh: '美国' },
  { city: 'Dallas', cityZh: '达拉斯', stadium: 'AT&T Stadium', stadiumZh: 'AT&T体育场', country: 'USA', countryZh: '美国' },
  { city: 'Kansas City', cityZh: '堪萨斯城', stadium: 'Arrowhead Stadium', stadiumZh: '箭头体育场', country: 'USA', countryZh: '美国' },
  { city: 'Atlanta', cityZh: '亚特兰大', stadium: 'Mercedes-Benz Stadium', stadiumZh: '梅赛德斯-奔驰体育场', country: 'USA', countryZh: '美国' },
  { city: 'Houston', cityZh: '休斯顿', stadium: 'NRG Stadium', stadiumZh: 'NRG体育场', country: 'USA', countryZh: '美国' },
  { city: 'Seattle', cityZh: '西雅图', stadium: 'Lumen Field', stadiumZh: '流明球场', country: 'USA', countryZh: '美国' },
  { city: 'Santa Clara', cityZh: '圣克拉拉', stadium: "Levi's Stadium", stadiumZh: '李维斯体育场', country: 'USA', countryZh: '美国' },
  { city: 'Philadelphia', cityZh: '费城', stadium: 'Lincoln Financial Field', stadiumZh: '林肯金融球场', country: 'USA', countryZh: '美国' },
  { city: 'Miami', cityZh: '迈阿密', stadium: 'Hard Rock Stadium', stadiumZh: '硬石体育场', country: 'USA', countryZh: '美国' },
  { city: 'Foxborough', cityZh: '福克斯堡', stadium: 'Gillette Stadium', stadiumZh: '吉列体育场', country: 'USA', countryZh: '美国' },
];
